# -*- coding: utf-8 -*-
"""rbi_liabilities_liquidity_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rbv4LSJFF_Q4eEMXRo291AGnm52zk4Ea
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/drive/MyDrive/RBI - Liabilities & Assets.csv")

df.head()

df = df.dropna(axis=1, how="all")

df.columns = [
    "Week_Ended",
    "Notes_Issue_Department",
    "Notes_Banking_Department",
    "Deposits",
    "Borrowings",
    "Capital",
    "Loans_Advances",
    "Investments",
    "Cash_Balances",
    "Other_Assets"
]

df.head()

df = df.iloc[2:].reset_index(drop=True)

df["Week_Ended"] = pd.to_datetime(df["Week_Ended"], dayfirst=True, errors='coerce')
df = df.dropna(subset=["Week_Ended"]).reset_index(drop=True)

numeric_cols = df.columns[1:]

for col in numeric_cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(",", "", regex=False)
        .astype(float)
    )

df = df.rename(columns={
    "Notes_Issue_Department": "Notes_in_Circulation",
    "Notes_Banking_Department": "Govt_Deposits",
    "Deposits": "MSS_Deposits",
    "Borrowings": "State_Govt_Deposits",
    "Capital": "SCB_Deposits",
    "Loans_Advances": "SSCB_Deposits",
    "Investments": "Non_SSCB_Deposits",
    "Cash_Balances": "Other_Bank_Deposits",
    "Other_Assets": "Other_Liabilities"
})

df.head()

df.info()

df["Week_Ended"] = pd.to_datetime(df["Week_Ended"])
df = df.sort_values("Week_Ended")
df = df.set_index("Week_Ended")

df.isna().sum()

df["MSS_Deposits"] = df["MSS_Deposits"].fillna(0)

df["Total_Liabilities"] = df.sum(axis=1)

df.describe().T

plt.figure(figsize=(10,5))
plt.plot(df.index, df["Notes_in_Circulation"], label="Notes in Circulation")
plt.plot(df.index, df["SCB_Deposits"], label="Scheduled Commercial Bank Deposits")
plt.plot(df.index, df["Other_Liabilities"], label="Other Liabilities")

plt.yscale("log")
plt.title("Key RBI Liabilities Over Time (Log Scale)")
plt.ylabel("₹ Crores (log scale)")
plt.xlabel("Date")
plt.legend()
plt.show()

share_df = df.div(df["Total_Liabilities"], axis=0) * 100

plt.figure(figsize=(10,5))

plt.stackplot(
    share_df.index,
    share_df["Notes_in_Circulation"],
    share_df["SCB_Deposits"],
    share_df["Other_Liabilities"],
    labels=["Notes in Circulation", "SCB Deposits", "Other Liabilities"]
)

plt.title("Composition of RBI Liabilities (%)")
plt.ylabel("Percentage Share")
plt.xlabel("Date")
plt.legend(loc="upper right")
plt.show()

df["Notes_Weekly_Change_%"] = df["Notes_in_Circulation"].pct_change() * 100

plt.figure(figsize=(10,4))
plt.plot(df.index, df["Notes_Weekly_Change_%"])
plt.axhline(0, color="black", linewidth=0.8)

plt.title("Weekly % Change in Notes in Circulation")
plt.ylabel("Percent Change")
plt.xlabel("Date")
plt.show()

corr = df[
    ["Notes_in_Circulation", "SCB_Deposits", "Other_Liabilities"]
].corr()

corr

summary = pd.DataFrame({
    "Average (₹ Cr)": df.mean(),
    "Std Dev (₹ Cr)": df.std(),
    "Share (%)": (df.mean() / df["Total_Liabilities"].mean()) * 100
})

summary.loc[
    ["Notes_in_Circulation", "SCB_Deposits", "Other_Liabilities"]
]

"""This analysis shows that the Reserve Bank of India’s liabilities are dominated by notes in circulation and deposits from scheduled commercial banks, which together account for the majority of total liabilities. While the absolute level of liabilities exhibits a steady long-term increase, the composition remains relatively stable over time, indicating a consistent structural framework of liquidity absorption.

However, weekly percentage changes in notes in circulation reveal periods of sharp short-term volatility that are not visible in aggregate trends. These fluctuations highlight that liquidity dynamics are driven more by transient shocks and operational factors than by gradual structural change. As a result, average growth measures alone are insufficient to understand liquidity behavior, and high-frequency balance-sheet data is essential for identifying stress episodes and abnormal movements in the monetary system.
"""

